basePath: /
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This service returns the highest prime number lower the input provided
    by user.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Nearest Prime API
  version: "1.0"
paths:
  /nearestprime:
    get:
      consumes:
      - '*/*'
      description: Gets the status of service.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Show the status of service.
      tags:
      - NearestPrime
  /nearestprime/{num}:
    get:
      consumes:
      - '*/*'
      description: Gets the highest prime number lower than the provided number.
      parameters:
      - description: Number
        in: path
        name: num
        required: true
        type: integer
      produces:
      - text/plain
      responses:
        "200":
          description: ""
      summary: Returns the highest prime number lower than the provided number.
      tags:
      - NearestPrime
schemes:
- http
swagger: "2.0"
